redefind _install

diff --git a/makepkgs-templates/base-build-1.template b/makepkgs-templates/base-build-1.template
--- a/makepkgs-templates/base-build-1.template
+++ b/makepkgs-templates/base-build-1.template
@@ -6,46 +6,107 @@ _stateDir=var/lib/${pkgname}
 _logDir=var/log/${pkgname}
 _licenseDir=usr/share/licenses/${pkgname}
 
-_commonPermissions="u=rwx,g=rx,o=rx u=rw,g=r,o=r"
-_securePermissions="u=rwx,g=rx,o= u=rw,g=r,o="
+_commonPermissions='u=rwx,g=rx,o=rx u=rw,g=r,o=r'
+_securePermissions='u=rwx,g=rx,o= u=rw,g=r,o='
 
-# _install user:group 777 666 [sourceFile|sourceDir] destDir
+
+# Strictly Formatted Installation
+#
+### Files
+# For clean documentation directories are not created automaticaly.
+#
+# (1) _install user:group ${_commonPermissions} newFile destDir/
+#     * Create Empty File In Destination-Directory
+#     => destDir/newFile
+#
+# (2) _install user:group ${_commonPermissions} sourceFile destDir/
+#     * Copy Source-File Into Destination-Directory
+#     => destDir/sourcFileName
+#
+# (3) _install user:group ${_commonPermissions} sourceFile destDir/destFileName
+#     * Copy Source-File Into Destinatin-Directory With New Name
+#     => destDir/destFileName
+#
+### Directories
+# For clean documentation parent directories are not created automaticaly.
+#
+# (4) _install user:group ${_commonPermissions} destDir/newDir
+#     * Create New Directory
+#     => destDir/newDir
+#
+# (5) _install user:group ${_commonPermissions} sourceDir destDir/
+#     * Copy Source-Directory Into Destination-Directory
+#     => destDir/sourceDirName
+#
+# (6) _install user:group ${_commonPermissions} sourceDir destDir
+#     * Copy Content of Source-Directory Into Destination-Directory
+#     => destDir/sourceDirContent
+#
 # https://www.shellbefehle.de/befehle/chmod/
 _install() {
     local _chown="$1"
     local _chmodDir="$2"
     local _chmodFile="$3"
 
+    ### Directories
+    # (4) Create New Directory
     if [ -z "$5" ];
     then
-        # create _destDir only
-        local _destDir="$4"
-        mkdir -p "${_destDir}"
-        chown ${_chown} ${_destDir}
-        chmod "${_chmodDir}" ${_destDir}
+	local _dest="$4"
+	_mkdirLeaf "${_dest}"
+	chown ${_chown} ${_dest}
+	chmod "${_chmodDir}" ${_dest}
+	return 0
+    fi
+
+    local _source=$4
+    local _dest=$5
+    if [ -d "${_source}" ];
+    then
+	if [[ ${_dest} == */ ]];
+	then
+	    # (5) Copy Source-Directory Into Destination-Directory
+	    _dest="${_dest}$(basename ${_source})"
+	    _mkdirLeaf "${_dest}"
+	fi
+	
+	# (5),(6) Copy Content of Source-Directory Into Destination-Directory
+	cp -fRT ${_source} ${_dest}
+	find ${_dest} -exec chown "${_chown}" {} \;
+	find ${_dest} -type f -exec chmod "${_chmodFile}" {} \;
+	find ${_dest} -type d -exec chmod "${_chmodDir}" {} \;
+	return 0
+    fi
+
+    ### Files
+    if [[ ${_dest} == */ ]];
+    then
+	# (2) Copy Source-File Into Destination-Directory
+	_dest=${_dest}$(basename ${_source})
+    fi
+
+    if [ ! -f "${_source}" ];
+    then
+	# (1) Create Empty File In Destination-Directory
+	touch ${_dest}
     else
-        # copy/create _source*
-        local _destDir="$5"
-        mkdir -p "${_destDir}"
+	# (1),(3) Copy Source-File Into Destinatin-Directory With New Name
+	cp -fL ${_source} ${_dest}
+    fi
+    chown ${_chown} ${_dest}
+    chmod "${_chmodFile}" ${_dest}
+}
 
-        if [ -d "$4" ];
-        then
-            local _sourceDir="$4"
-            cp -RT ${_sourceDir} ${_destDir}
-            find ${_destDir} -exec chown "${_chown}" {} \;
-            find ${_destDir} -type f -exec chmod "${_chmodFile}" {} \;
-            find ${_destDir} -type d -exec chmod "${_chmodDir}" {} \;
-
-        else
-            local _sourceFile="$4"
-            if [ ! -f "${_sourceFile}" ];
-            then
-                touch ${_destDir}/$(basename ${_sourceFile})
-            else
-                cp -L ${_sourceFile} ${_destDir}
-            fi
-            chown ${_chown} ${_destDir}/$(basename ${_sourceFile})
-            chmod "${_chmodFile}" ${_destDir}/$(basename ${_sourceFile})
-        fi
+_mkdirLeaf() {
+    local _dest=$1
+    if [ ! -e "$(dirname ${_dest})" ];
+    then
+        echo "Parent Directory not found $(dirname ${_dest})"
+        exit 1
+    fi
+    if [ ! -e "${_dest}" ];
+    then
+        mkdir "${_dest}"
     fi
 }
+
